# Generated by Django 3.1.1 on 2020-10-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Userid',
            new_name='userid',
        ),
    ]
