# Generated by Django 3.1.1 on 2020-11-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201025_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
                ('discountlimit', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='discountid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.discount'),
        ),
    ]
