# Generated by Django 3.1.1 on 2020-10-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='orderno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
