# Generated by Django 3.1.1 on 2020-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailtemplateid', models.CharField(max_length=100)),
                ('subject', models.TextField(max_length=100)),
                ('header', models.TextField(max_length=100)),
                ('body', models.TextField(max_length=100)),
                ('footer', models.TextField(max_length=100)),
                ('subscribe', models.TextField(max_length=100)),
                ('attachment', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('targetarea', models.TextField(max_length=100)),
                ('targetage', models.TextField(max_length=100)),
                ('previousemaildate', models.DateTimeField(auto_now_add=True)),
                ('emaildate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
