# Generated by Django 3.1.1 on 2020-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='imageType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
