# Generated by Django 3.1.1 on 2020-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_document_imagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='photos/')),
                ('imageType', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
