# Generated by Django 3.1.1 on 2020-10-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201025_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='docfile',
            new_name='photofile',
        ),
    ]
