# Generated by Django 3.1.1 on 2020-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(max_length=100)),
                ('orderid', models.CharField(max_length=100)),
                ('paymentmethod', models.TextField(max_length=100)),
                ('gatewaytransactionid', models.TextField(max_length=100)),
                ('transactionstatus', models.TextField(max_length=100)),
                ('transactiondate', models.TextField(max_length=100)),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
