# Generated by Django 3.1.1 on 2020-10-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201025_1730'),
        ('transactions', '0002_auto_20201010_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='gatewaytransactionid',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='paymentmethod',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactiondate',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactionstatus',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
