# Generated by Django 3.1.1 on 2020-10-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customerid',
            new_name='userid',
        ),
    ]
