# Generated by Django 3.1.1 on 2020-10-10 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_auto_20201010_1115'),
        ('products', '0001_initial'),
        ('orders', '0002_auto_20201010_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='discountid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orderid',
        ),
        migrations.AlterField(
            model_name='orders',
            name='addressid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
