# Generated by Django 3.1.1 on 2020-12-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20201224_1815'),
        ('orders', '0004_auto_20201025_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='productid',
        ),
        migrations.AddField(
            model_name='orders',
            name='cartid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
