# Generated by Django 3.1.1 on 2020-10-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('discountlimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('6X4', '6X4'), ('5X5', '5X5'), ('7X5', '7X5'), ('8X6', '8X6')], max_length=100)),
                ('papertype', models.CharField(max_length=100)),
                ('unitprice', models.FloatField()),
                ('type', models.CharField(choices=[('PHOTO', 'Photo Print'), ('DOC', 'Document print')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('discountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.discount')),
                ('priceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.price')),
            ],
        ),
    ]
