# Generated by Django 3.1.1 on 2020-10-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201025_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='details',
            new_name='papertype',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='productname',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discountid',
        ),
        migrations.RemoveField(
            model_name='products',
            name='priceid',
        ),
        migrations.AddField(
            model_name='products',
            name='producttype',
            field=models.CharField(choices=[('PHOTO', 'Photo Print'), ('DOC', 'Document print')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sizename',
            field=models.CharField(choices=[('6X4', '6X4'), ('5X5', '5X5'), ('7X5', '7X5'), ('8X6', '8X6')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='unitprice',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
