# Generated by Django 3.1.1 on 2020-10-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201025_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sizename',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
