# Generated by Django 3.1.1 on 2020-10-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='staus',
            new_name='status',
        ),
    ]
